AWSTemplateFormatVersion: '2010-09-09'
Description: 'This solution consists of a lambda functions which is used to fetch
  logs from Slack and ingest to Sumo Logic.

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Author: Sumo Logic
    Description: This solution consists of a lambda functions which is used to fetch
      logs from Slack and ingest to Sumo Logic.
    HomePageUrl: https://github.com/SumoLogic/sumologic-slack
    Labels:
    - lambda
    - sumologic
    - serverless
    - Slack
    LicenseUrl: s3://appdevstore/Slack/v1.0.1/5122657d5b9a0d3713e24d3a33eae431
    Name: sumologic-slack
    ReadmeUrl: s3://appdevstore/Slack/v1.0.1/a4f6f2ba5f0edde2440caf90e81ea530
    SemanticVersion: 1.0.1
    SourceCodeUrl: https://github.com/SumoLogic/sumologic-slack
    SpdxLicenseId: Apache-2.0
Outputs:
  SlackFunction:
    Description: SlackScheduler Function ARN
    Value:
      Fn::GetAtt:
      - SlackFunction
      - Arn
Parameters:
  HttpLogsEndpoint:
    Type: String
  Token:
    Type: String
Resources:
  SlackFunction:
    Properties:
      CodeUri: s3://appdevstore/Slack/v1.0.1/43beec6bd8c8896344b2c06d28c95123
      Environment:
        Variables:
          ENVIRONMENT: aws
          HTTP_LOGS_ENDPOINT:
            Ref: HttpLogsEndpoint
          TOKEN:
            Ref: Token
      Events:
        ScheduleRule:
          Properties:
            Schedule: rate(10 minutes)
          Type: Schedule
      Handler: main.main
      Layers:
      - Fn::Sub: arn:aws:lambda:${AWS::Region}:956882708938:layer:Slack-deps:5
      MemorySize: 256
      Policies:
      - AmazonDynamoDBFullAccess
      Runtime: python3.7
      Timeout: 900
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
